//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravenous.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meal_images
    {
        public int restaurantId { get; set; }
        public int mealId { get; set; }
        public string mealImage { get; set; }
    
        public virtual meal meal { get; set; }
    }
}
