//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravenous.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meal
    {
        public int restaurantId { get; set; }
        public int Id { get; set; }
        public string mealName { get; set; }
        public double mealPrice { get; set; }
        public int category { get; set; }
        public string mealImage { get; set; }
        public bool available { get; set; }
    
        public virtual mealCategory mealCategory { get; set; }
        public virtual ownerRestaurant ownerRestaurant { get; set; }
    }
}
