//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravenous.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ownerRestaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ownerRestaurant()
        {
            this.meals = new HashSet<meal>();
            this.Tables = new HashSet<Table>();
        }
    
        public int Id { get; set; }
        public string email { get; set; }
        public string restaurantName { get; set; }
        public string restaurantPhone { get; set; }
        public int country { get; set; }
        public string location { get; set; }
        public bool isAvailableForOccasion { get; set; }
        public bool isAvailableForKids { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string image { get; set; }
        public bool isApproved { get; set; }
    
        public virtual country country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meal> meals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table> Tables { get; set; }
    }
}
