//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravenous.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int restaurantId { get; set; }
        public int Id { get; set; }
        public int tableNo { get; set; }
        public int chairsNo { get; set; }
        public bool isReserved { get; set; }
    
        public virtual ownerRestaurant ownerRestaurant { get; set; }
    }
}
